name: Release BeeSettingsEditor

on:
  push:
    tags:
      - 'BeeSettingsEditor-v*'

env:
  PUBLISH_DIR: src/BeeSettingsEditor/bin/Release/net10.0-windows/publish/win-x64

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Publish BeeSettingsEditor
      run: |
        dotnet publish src/BeeSettingsEditor/BeeSettingsEditor.csproj `
          -c Release `
          /p:PublishProfile=FolderProfile

    - name: List publish output
      run: Get-ChildItem -Path ${{ env.PUBLISH_DIR }} -Recurse | Select-Object FullName

    - name: Create zip package
      run: |
        Compress-Archive `
          -Path "${{ env.PUBLISH_DIR }}\*" `
          -DestinationPath ${{ github.ref_name }}.zip

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: ${{ github.ref_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
