name: Release BeeSettingsEditor

on:
  push:
    tags:
      - 'BeeSettingsEditor-v*'

permissions:
  contents: write

env:
  PUBLISH_DIR: publish-output

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Publish BeeSettingsEditor
      run: |
        dotnet publish src\BeeSettingsEditor\BeeSettingsEditor.csproj `
          -c Release `
          -r win-x64 `
          --self-contained false `
          -p:PublishSingleFile=true `
          -p:PublishReadyToRun=false `
          -p:DebugType=none `
          -p:PublishDir=${{ github.workspace }}\${{ env.PUBLISH_DIR }}\

    - name: Remove extra artifacts
      run: |
        Get-ChildItem "${{ env.PUBLISH_DIR }}" -Filter *.xml | Remove-Item
        Get-ChildItem "${{ env.PUBLISH_DIR }}" -Filter *.pdb | Remove-Item

    - name: Create zip package
      run: |
        Compress-Archive `
          -Path "${{ env.PUBLISH_DIR }}\*" `
          -DestinationPath "${{ github.ref_name }}.zip"

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: ${{ github.ref_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
